version: "2"

services:
  web:
    build: .
    command: sleep 9999 # remove when deploying to prod
    environment:
      - NODE_ENV=${NODE_ENV}
      - SLACK_ID=${SLACK_ID}
      - TERM=xterm
    volumes:
      - "./:/app/"
    ports:
      - "3000:3000"

